import 'anjing.dart';
import 'burung.dart';
import 'ikan.dart';
import 'srigala.dart';
void main(){
  Anjing hewan1 = Anjing(jumlahKaki: 4, berat: 10);
  print("Hewan 1 : ${hewan1.kategori} - ${hewan1.nama}");
  print("${hewan1.berat} Kg");
  hewan1.setlari = 10;
  hewan1.setrenang = 20;
  print("Lari : ${hewan1.lari} Km/Jam");
  print("Renang : ${hewan1.renang} Km/Jam");
  print("${hewan1.jumlahKaki} Kaki");
  print("------MAKAN 2 Kg-------");
  hewan1.makan = 2;
  print("SEKARANG ${hewan1.berat} Kg");
  print("\n===============\n");
  Ikan hewan2 = Ikan(berat: 2);
  hewan2.setrenang = 7;
  print("Hewan 2 : ${hewan2.kategori} - ${hewan2.nama}");
  print("${hewan2.berat} Kg");
  print("${hewan2.renang} Km/Jam");
  print("------Makan 5 kg---------");
  hewan2.makan = 5;
  print("SEKARANG ${hewan2.berat} Kg");
  print("\n===============\n");
  Burung hewan3 = Burung(berat: 2, jumlahKaki: 2 );
  hewan3.setterbang = 40;
  print("Hewan 3 : ${hewan3.kategori} - ${hewan3.nama}");
  print("Berat ${hewan3.berat} Kg");
  print("Kecepatan Terbang ${hewan3.terbang} Km/Jam");
  print("Jumlah ${hewan3.jumlahKaki} Kaki");
  print("------Makan 7 kg---------");
  hewan3.makan = 7;
  print("SEKARANG ${hewan3.berat} Kg");
  print("\n===============\n");
  Srigala hewan4 = Srigala(berat: 2, jumlahKaki: 2);
  hewan4.setlari = 40;
  hewan4.setrenang = 30;
  print("Hewan 4 : ${hewan4.kategori} - ${hewan4.nama}");
  print("Berat ${hewan4.berat} Kg");
  print("Kecepatan Renang ${hewan4.renang} Km/Jam");
  print("Kecepatan Lari ${hewan4.lari} Km/Jam");
  print("------Makan 8 kg---------");
  hewan4.makan = 8;
  print("SEKARANG ${hewan4.berat} Kg");
  print("\n===============\n");
}